fourfit-sistema_gestao.UI/Models/AvaliacaoFisica/AvaliacaoFisica.cs
using fourfit.sistema_gestao.Domain.Entities.Account;

namespace fourfit_sistema_gestao.UI.Models.AvaliacaoFisica
{
    public class AvaliacaoFisica
    {
        public int Id { get; set; }
        public User User { get; set; }
        public string? UserId { get; set; }
        public DateTime Data { get; set; }
        public bool Ativo { get; set; }
        public string Peso { get; set; }
        public string Busto { get; set; }
        public string? Cintura { get; set; }
        public string? Barriga { get; set; }
        public string? Quadril { get; set; }
        public string? PernaDireita { get; set; }
        public string? PernaEsqueda { get; set; }
        public string? BracoDireita { get; set; }
        public string? BracoEsquerdo { get; set; }
        public string? Imc { get; set; }
        public string? GorduraCorporal { get; set; }
        public string? MassaMagra { get; set; }
        public string? GorduraViceral { get; set; }
        public string? CaloriaBasal { get; set; }
        public string? IdadeMetabolica { get; set; }
        public string? Observacao { get; set; }
    }
}

fourfit-sistema_gestao.UI/Controllers/AvaliacaoFisicaController.cs
using Microsoft.AspNetCore.Mvc;

namespace fourfit_sistema_gestao.UI.Controllers
{
    public class AvaliacaoFisicaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

fourfit-sistema_gestao.UI/Views/AvaliacaoFisica/Index.cshtml
@model IEnumerable<AvaliacaoFisica>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

@Html.AntiForgeryToken()


<div class="container">
    <div class="custom"></div>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <form class="form-inline d-flex" method="get" action="@Url.Action("Index", "AvaliacaoFisica")">

            <input type="text" class="form-control mr-2" placeholder="Pesquisar Avaliação ..." name="searchString" value="@ViewBag.CurrentFilter">
            <button type="submit" class="btn btn-outline-dark">Buscar</button>

        </form>
        @*@if (User.IsInRole("Colaboradores") || User.IsInRole("Admin"))*@

        <button type="button" onclick="location.href='@Url.Action("CadastroAvaliacaoFisica","AvaliacaoFisica")'" class="btn btn-outline-dark"> <i class="bi bi-plus"></i> Nova Avaliacao Fisica</button>
    </div>

    <br /><br />
</div>
<div class="card">


    <div class="card-header">
        <div class="card-title">
        </div>
    </div>
    <div class="card-body">
        @TempData["Msg"]
        <table class="table">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Peso</th>
                    <th>Busto</th>
                    <th>Cintura</th>
                    <th>Barriga</th>
                    <th>Quadril</th>
                    <th>Ações</th>


                </tr>
            </thead>
            @* <tbody>
                @if (@Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Data</td>
                            <td>@item.User</td>

                            <td>
                                <button class="btn btn-outline-danger btnExcluir" title="Excluir" data-id="@item.Id"><i class="fa-solid fa-user-xmark"></i></button>
                            </td>
                        </tr>
                    }
                }

            </tbody> *@
        </table>
    </div>
</div>

</div>

@section scripts {
    <script>

        $('.btnExcluir').on('click', function () {
            if (confirm("Deseja excluir?")) {
                var id = $(this).attr("data-id");
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("ExcluirAvaliacaoFisica", "AvaliacaoFisica")',
                    data: { Id: id },
                    success: function (response) {
                        if (response.sucesso) {
                            alert(response.mensagem);
                            window.location.href = '@Url.Action("Index", "AvaliacaoFisica")';

                        }

                    }, error: function () {

                    }
                });
            }


        });

    </script>
}>