fourfit-sistema_gestao.UI/Controllers/AlunosController.cs
using fourfit.sistema_gestao.Domain.Entities.Alunos;
using fourfit.sistema_gestao.Domain.Interfaces;
using fourfit_sistema_gestao.UI.Models.Alunos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace fourfit_sistema_gestao.UI.Controllers
{
    //[Authorize]
    public class AlunosController : Controller
    {

        private readonly IUnitOfWork _unitOfwork;

        public AlunosController(IUnitOfWork unitOfwork)
        {

            _unitOfwork = unitOfwork;
        }
        
        public async Task<IActionResult> Index(string searchString)
        
        
        {
            ViewBag.CurrentFilter = searchString;

            var resultado = await _unitOfwork.AlunosServices.ObterAlunosExistentes();

            //if (!string.IsNullOrEmpty(searchString))
            //{
            //    resultado = resultado.Where(x => x.User.NomeCompleto.Contains(searchString));
            //}

            return View(resultado.ToList());

        }
        
        public async Task<IActionResult> CadastroAlunos()
        {
            var usuarios = await _unitOfwork.UserServices.ObterUsuariosComEmailConfirmado();
            ViewBag.Usuario = new SelectList(usuarios.Select(x => new
            {
                x.Id,
                x.PrimeiroNome,
            }), "Id", "PrimeiroNome");


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CadastroAlunos(AlunosViewModel alunosViewModel)
        {
            try
            {
                var CpfRemoverMascara = alunosViewModel.Cpf.ToString().Replace(".", "").Replace("-", "");
                var model = new EntidadeAlunos
                {
                    UserId = alunosViewModel.UserId,
                    //Cpf = Convert.ToInt64(CpfRemoverMascara),
                    Foto = alunosViewModel.Foto,
                    Cep = alunosViewModel.Cep,
                    Endereco = alunosViewModel.Endereco,
                    Numero = alunosViewModel.Numero,
                    Bairro = alunosViewModel.Bairro,
                    Cidade = alunosViewModel.Cidade,
                    Estado = alunosViewModel.Estado,
                    DataNacimento = alunosViewModel.DataNacimento,
                    DataCadastro = DateTime.Now,
                    
                };
                await _unitOfwork.AlunosServices.Cadastro(model);
                TempData["Msg"] = "Alunos cadastrado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public async Task<IActionResult> AlterarAlunos(int Id)
        {
            var alunosComUsuarios = await _unitOfwork.AlunosServices.ObterAlunosUsuariosPorId(Id);
            
            var alunosView = new AlunosEdicaoViewModel
            {
                Id = alunosComUsuarios.Id,
                PrimeiroNome = alunosComUsuarios.User.PrimeiroNome,
                Cpf = alunosComUsuarios.Bairro,
                Celular = alunosComUsuarios.Celular,
                Cep = alunosComUsuarios.Cep,
                Endereco = alunosComUsuarios.Endereco,
                Numero = alunosComUsuarios.Numero,
                Bairro = alunosComUsuarios.Bairro,
                Cidade = alunosComUsuarios.Cidade,
                Estado = alunosComUsuarios.Estado,
                DataNacimento = alunosComUsuarios.DataNacimento,
               
               

            };

            if (alunosComUsuarios != null)
            {
                return View(alunosView);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AlterarAlunos(AlunosEdicaoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var alunos = await _unitOfwork.AlunosServices.ObterPorId(model.Id);
                    if (alunos != null)
                    {
                        var usuario = await _unitOfwork.UserServices.ObterPorUserId(alunos.UserId);

                        if (usuario != null)
                        {
                            //alunos.Cpf = model.Bairro;
                            alunos.Celular = model.Celular;
                            alunos.Cep = model.Cep;
                            alunos.Endereco = model.Endereco;
                            alunos.Bairro = model.Bairro;
                            alunos.Numero = model.Numero;
                            alunos.Cidade = model.Cidade;
                            alunos.Estado = model.Estado;
                            alunos.DataNacimento = model.DataNacimento;
                            usuario.PrimeiroNome = model.PrimeiroNome;
                            await _unitOfwork.AlunosServices.Atualizar(alunos);
                            await _unitOfwork.UserServices.Atualizar(usuario);
                        }
                    }
                    else
                    {
                        ViewBag.Msg = "Não há dados.";
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public async Task<JsonResult> ExcluirAluno(int id)
        {
            try
            {
                var aluno = await _unitOfwork.AlunosServices.ObterPorId(id);
                if (aluno != null)
                {
                    await _unitOfwork.AlunosServices.Deletar(id);
                    return Json(new { sucesso = true, mensagem = "Aluno excluído com sucesso" });
                }
                else
                {
                    return Json(new { sucesso = false, mensagem = "Aluno não existe" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { sucesso = false, mensagem = "Ocorreu um erro ao excluir o aluno: " + ex.Message });
            }
        }

    }
}

fourfit-sistema_gestao.UI/Controllers/CheckinController.cs
using fourfit.sistema_gestao.Domain.Entities;
using fourfit.sistema_gestao.Domain.Interfaces;
using fourfit_sistema_gestao.UI.Models.Checkins;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace fourfit_sistema_gestao.UI.Controllers
{
    public class CheckinController : Controller
    {
        private readonly IUnitOfWork _unitOfwork;


        public CheckinController(IUnitOfWork unitOfwork)
        {

            _unitOfwork = unitOfwork;
        }
        public async Task<IActionResult> Index()
        {
            var resultado = await _unitOfwork.CheckinsServices.ObterCheckinExistentes();
            return View(resultado.ToList());
        }

        public async Task<IActionResult> CadastroCheckin()
        {
            var usuarios = await _unitOfwork.UserServices.ObterUsuariosComEmailConfirmado();
            //ViewBag.Usuario = new SelectList(usuarios.Select(x => new
            //{
            //    x.Id,
            //    x.NomeCompleto,
            //}), "Id", "NomeCompleto");

            return View(); 
        }
        [HttpPost]
        public  async Task<IActionResult> CadastroCheckin(CheckinViewModel checkinViewModel)
        {
            try
            {
                //var model = new Checkins
                {
                 
                    //Data = DateTime.Now,
                    
                };
                //await _unitOfwork.CheckinServices.Cadastro(model);
                TempData["Msg"] = "Checkin cadastrado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

fourfit-sistema_gestao.UI/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace fourfit_sistema_gestao.UI.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
      
        public IActionResult BemVindo()
        {
            ///fsdfsdfsfsf
            ///
            /*
             sdfsdfsfdsdffsd
             
             sf*/
            return View();
        }
    }
}

fourfit-sistema_gestao.UI/Controllers/DespesasController.cs
using fourfit.sistema_gestao.Domain.Entities.Alunos;
using fourfit.sistema_gestao.Domain.Entities.Financas;
using fourfit.sistema_gestao.Domain.Interfaces;
using fourfit_sistema_gestao.UI.Models.Alunos;
using fourfit_sistema_gestao.UI.Models.Financas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace fourfit_sistema_gestao.UI.Controllers
{
    public class DespesasController : Controller
    {
        private readonly IUnitOfWork _unitOfwork;

        public DespesasController(IUnitOfWork unitOfwork)
        {

            _unitOfwork = unitOfwork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> CadastroDespesas()
        {
            var usuarios = await _unitOfwork.UserServices.ObterUsuariosComEmailConfirmado();
            //ViewBag.Usuario = new SelectList(usuarios.Select(x => new
            //{
            //    x.Id,
            //    x.NomeCompleto,
            //}), "Id", "NomeCompleto");


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CadastroDespesas(DespesasViewModel despesasViewModel)
        {
            try
            {
                var model = new Despesas
                {
                   //Valor = despesasViewModel.Valor,
                   // Tipo = despesasViewModel.Tipo,
                   // Vencimento = DateTime.Now,
                   // Pagamento = DateTime.Now,
                    
                };
                await _unitOfwork.DespesasServices.Cadastro(model);
                TempData["Msg"] = "Despesa cadastrado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

fourfit-sistema_gestao.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Four Fit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/all.css" />
   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fourfit_sistema_gestao.UI.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="../images/logo.png" width="5%" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <form id="logoutForm" asp-controller="Account" asp-action="Logout" method="post">
                    <button type="submit" class="btn btn-warning">Sair</button>
                    </form>
                }
                else
                {
                   
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-check"></i> Login
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Login">Entrar</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Cadastro">Nova Conta</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Four Fit
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/all.min.js" asp-append-version="true"></script>
    <script src="~/js/cadastro.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
    <script src="~/js/CadastroAluno.js" asp-append-version="true"></script>
   
    
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>

fourfit-sistema_gestao.UI/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Four Fit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/all.css" />
    <link rel="stylesheet" href="~/css/Home.css"/>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fourfit_sistema_gestao.UI.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="~/images/logo.png" alt="logo" width="5%"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                   
                    <form class="d-flex">
                       
                            <li class="nav-item dropdown">
                                <a class="btn btn-danger dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-user-gear"></i> Login
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-action="Login" asp-controller="Account"><i class="fa-solid fa-right-to-bracket"></i> Entrar</a></li>
                                     <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-action="Cadastro" asp-controller="Account"><i class="fa-solid fa-user-plus"></i> Nova conta</a></li>
                                </ul>
                            </li>
                      

                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Four Fit
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/all.min.js" asp-append-version="true"></script>
    <script src="~/js/cadastro.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
    <script src="~/js/CadastroAluno.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

fourfit-sistema_gestao.UI/Views/Shared/_LayoutPrincipal.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Four Fit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/all.css" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fourfit_sistema_gestao.UI.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <div class="sidbar">
                    <div class="sidbar-title">
                        <img src="../images/avatar-anonimo.png" />
                        @User.Identity.Name
                    </div>

                    <ul>

                        <li><a asp-action="BemVindo" asp-controller="Dashboard"><i class="fas fa-home icon-spacing"></i>Dashboard</a></li>

                        <li class="menu-item">
                            <a asp-action="#" asp-controller="Cadastro"><i class="fas fa-file-alt icon-spacing "></i>Cadastros <span class="caret"></span></a>
                            <ul class="submenu">
                                <li>
                                    <a asp-action="Index" asp-controller="Modalidades">
                                        <i class="fas fa-dumbbell icon-spacing"></i>
                                        Modalidades
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Planos">
                                        <i class="fas fa-clipboard-list icon-spacing"></i>
                                        Planos
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="AvaliacaoFisica">
                                        <i class="fas fa-heartbeat icon-spacing"></i>
                                        Avaliação Física
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="menu-item">
                            <a asp-action="#" asp-controller="Usuarios"><i class="fas fa-users icon-spacing"></i>Usuários</a>
                            <ul class="submenu">
                                <li>
                                    <a asp-action="Index" asp-controller="Alunos">
                                        <i class="fas fa-user-graduate icon-spacing"></i>
                                        Alunos
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Professores">
                                        <i class="fas fa-chalkboard"></i>
                                        Professores
                                    </a>
                                </li>
                                <li><a asp-action="Index" asp-controller="Colaboradores"><i class="fas fa-user-tie icon-spacing"></i>Colaboradores</a></li>
                            </ul>
                        </li>
                        <li><a asp-action="Index" asp-controller="Checkin"><i class="fas fa-check icon-spacing"></i>Checkin</a></li>
                        <li><a href="#"><i class="fas fa-calendar-alt icon-spacing"></i>Mensalidades</a></li>
                        <li class="menu-item">
                            <a href="#"><i class="fa-solid fa-dollar-sign icon-spacing"></i>Finanças</a>
                            <ul class="submenu">
                                <li><a asp-action="Index" asp-controller="Despesas"><i class="fas fa-receipt icon-spacing"></i>Despesas</a></li>
                                <li><a asp-action="Index" asp-controller="Investimentos"><i class="fas fa-piggy-bank icon-spacing"></i>Investimentos</a></li>
                            </ul>
                            </li>
                        <li><a href="#"><i class="fas fa-chart-bar icon-spacing"></i>Relatórios</a></li>
                        <li class="menu-item">
                            <a href="#"><i class="fas fa-store icon-spacing"></i>Loja</a>
                            <ul class="submenu">
                                <li><a asp-action="Index" asp-controller="Estoque"><i class="fas fa-warehouse icon-spacing"></i>Estoque</a></li>
                                <li><a asp-action="Index" asp-controller="Vendas"><i class="fas fa-shopping-cart icon-spacing"></i>Vendas</a></li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fas fa-tablet-alt icon-spacing"></i>Meus Dispositivos</a></li>
                        <li><a href="#"><i class="fas fa-cogs icon-spacing"></i>Configuraçães</a></li>


                    </ul>

                </div>
            </div>
            <div class="col-10">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>


    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Four Fit
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/menu.js" asp-append-version="true"></script>
    <script src="~/js/all.min.js" asp-append-version="true"></script>
    <script src="~/js/cadastro.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
    <script src="~/js/CadastroAluno.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>