fourfit-sistema_gestao.UI/Models/Financas/InvestimentosViewModel.cs
using fourfit.sistema_gestao.Domain.Entities.Financas;

namespace fourfit_sistema_gestao.UI.Models.Financas
{
    public class InvestimentosViewModel
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Descricao { get; set; }
        public int Valor { get; set; }
        public DateTime Vencimento { get; set; }
        public DateTime Pagamento { get; set; }
        public int FormaPagamentoId { get; set; }
        public bool Ativo { get; set; }
        public string Observacao { get; set; }
    }
}

fourfit-sistema_gestao.UI/Controllers/InvestimentosController.cs
using fourfit.sistema_gestao.Domain.Entities.Financas;
using fourfit.sistema_gestao.Domain.Interfaces;
using fourfit_sistema_gestao.UI.Models.Financas;
using Microsoft.AspNetCore.Mvc;

namespace fourfit_sistema_gestao.UI.Controllers
{
    public class InvestimentosController : Controller
    {
        private readonly IUnitOfWork _unitOfwork;

        public InvestimentosController(IUnitOfWork unitOfwork)
        {

            _unitOfwork = unitOfwork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> CadastroInvestimentos()
        {
            var usuarios = await _unitOfwork.UserServices.ObterUsuariosComEmailConfirmado();
            //ViewBag.Usuario = new SelectList(usuarios.Select(x => new
            //{
            //    x.Id,
            //    x.NomeCompleto,
            //}), "Id", "NomeCompleto");


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CadastroInvestimentos(InvestimentosViewModel investimentosViewModel)
        {
            try
            {
                var model = new Investimentos
                {
                    //Valor = investimentosViewModel.Valor,
                    //Tipo = investimentosViewModel.Tipo,
                    //Vencimento = DateTime.Now,
                    //Pagamento = DateTime.Now,
                
                };
                await _unitOfwork.InvestimentosServices.Cadastro(model);
                TempData["Msg"] = "Investimento cadastrado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

fourfit-sistema_gestao.UI/Views/Investimentos/CadastroInvestimentos.cshtml
@model InvestimentosViewModel

@{
    ViewData["Title"] = "CadastroInvestimetos";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CadastroInvestimentos" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label"></label>
                    <select asp-for="Id" class="form-select" asp-items="@ViewBag.Usuario">
                        <option selected value="0">Selecione o Usuário</option>
                    </select>
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>


            </form>
        </div>
    </div>
</div>


<div>
    <a class="btn bnt-dark" asp-action="Index">Voltar</a>
</div>

fourfit-sistema_gestao.UI/Views/Investimentos/Index.cshtml
@model IEnumerable<Investimentos>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
@Html.AntiForgeryToken()


<div class="container">
    <h2>Gerenciador de Investimentos</h2>

    <div class="custom"></div>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <form class="form-inline d-flex" method="get" action="@Url.Action("Index", "Investimentos")">

            <input type="text" class="form-control mr-2" placeholder="Pesquisar Investimento..." name="searchString" value="@ViewBag.CurrentFilter">
            <button type="submit" class="btn btn-outline-dark">Buscar</button>

        </form>
        @if (User.IsInRole("Colaboradores") || User.IsInRole("Admin"))
        {
            <button type="button" onclick="location.href='@Url.Action("CadastroInvestimentos","Investimentos")'" class="btn btn-outline-dark"> <i class="bi bi-plus"></i> Novo Investimento</button>
        }

    </div>

    <br /><br />
</div>
<div class="card">


    <div class="card-header">
        <div class="card-title">
        </div>
    </div>
    <div class="card-body">
        @TempData["Msg"]
        <table class="table">
            <thead>
                <tr>
                    <th>Foto</th>
                    <th>Nome</th>
                    <th>Status</th>
                    <th>Cpf</th>
                    <th>Observaçães</th>
                    <th>Ações</th>
                </tr>
            </thead>
            @* <tbody>
                @if (@Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Foto</td>
                            <td>@item.User.NomeCompleto</td>


                            @if (item.Ativo == true)
                            {
                                <td style="color:darkslategrey">ATIVO</td>
                            }
                            else
                            {
                                <td style="color:red">INATIVO</td>
                            }
                            <td>@item.Cpf</td>
                            <td>@item.Observacaes</td>
                            <td>
                                <button class="btn btn-outline-warning" title="Editar" onclick="window.location.href ='@Url.Action("AlterarColaboradores","Colaboradores", new {Id = item.Id})'">
                                    <i class="fa-solid fa-user-pen"></i>
                                </button>
                                <button class="btn btn-outline-danger btnExcluir" title="Excluir" data-id="@item.Id"><i class="fa-solid fa-user-xmark"></i></button>
                            </td>
                        </tr>
                    }
                }

            </tbody> *@
        </table>
    </div>
</div>

</div>

@section scripts {
    <script>

        $('.btnExcluir').on('click', function () {
            if (confirm("Deseja excluir?")) {
                var id = $(this).attr("data-id");
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("ExcluirInvestimento", "Investimentos")',
                    data: { Id: id },
                    success: function (response) {
                        if (response.sucesso) {
                            alert(response.mensagem);
                            window.location.href = '@Url.Action("Index", "Investimentos")';

                        }

                    }, error: function () {

                    }
                });
            }


        });

    </script>
}