fourfit-sistema_gestao.UI/Models/Colaboradores/ColaboradoresEdicaoViewModel.cs
namespace fourfit_sistema_gestao.UI.Models.Colaboradores
{
    public class ColaboradoresEdicaoViewModel
    {
        public int Id { get; set; }
       
        public string? NomeCompleto { get; set; }
        //public long Cpf { get; set; }
        public bool Ativo { get; set; }
        public byte[]? Foto { get; set; }
        public string? Observacaes { get; set; }
    }
}

fourfit-sistema_gestao.UI/Models/Colaboradores/ColaboradoresIndexViewModel.cs
namespace fourfit_sistema_gestao.UI.Models.Colaborador
{
    public class ColaboradoresIndexViewModel
    {
    }
}

fourfit-sistema_gestao.UI/Models/Colaboradores/ColaboradoresViewModel.cs
using fourfit.sistema_gestao.Domain.Entities.Account;

namespace fourfit_sistema_gestao.UI.Models.Colaboradores
{
    public class ColaboradoresViewModel
    {
        public int Id { get; set; }
        public string? UserId { get; set; }
        public string? NomeCompleto { get; set; }
        public long Cpf { get; set; }
        public bool Ativo { get; set; }
        public byte[]? Foto { get; set; }
        public string? Observacaes { get; set; }
    }
}

fourfit-sistema_gestao.UI/Controllers/ColaboradoresController.cs
using fourfit.sistema_gestao.Domain.Entities.Profission;
using fourfit.sistema_gestao.Domain.Interfaces;
using fourfit_sistema_gestao.UI.Models.Colaboradores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace fourfit_sistema_gestao.UI.Controllers
{
    [Authorize]
    public class ColaboradoresController : Controller
    {
        private readonly IUnitOfWork _unitOfwork;


        public ColaboradoresController(IUnitOfWork unitOfwork)
        {

            _unitOfwork = unitOfwork;
        }
        public async Task<IActionResult> Index()
        {
            var resultado = await _unitOfwork.ColaboradoresServices.ObterColaboradoresExistentes();
            return View(resultado.ToList());
        }
        [Authorize(Roles ="Colaboradores, Admin")]
        public async Task<IActionResult> CadastroColaboradores()
        {
            var usuarios = await _unitOfwork.UserServices.ObterUsuariosComEmailConfirmado();
            //ViewBag.Usuario = new SelectList(usuarios.Select(x => new
            //{
            //    x.Id,
            //    x.NomeCompleto,
            //}), "Id", "NomeCompleto");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CadastroColaboradores(ColaboradoresViewModel colaboradoresViewModel)
        {
            try
            {
                var model = new EntidadeColaboradores
                {
                    UserId = colaboradoresViewModel.UserId,
                    Foto = colaboradoresViewModel.Foto,
                  
                    
                };
                await _unitOfwork.ColaboradoresServices.Cadastro(model);
                TempData["Msg"] = "Colaborador cadastrado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task<IActionResult> AlterarColaboradores(int Id)
        {
            var colaboradoresComUsuarios = await _unitOfwork.ColaboradoresServices.ObterColaboradoresUsuariosPorId(Id);



            var colaboradoresView = new ColaboradoresEdicaoViewModel
            {
                Id = colaboradoresComUsuarios.Id,
                NomeCompleto = colaboradoresComUsuarios.User.PrimeiroNome,
                Foto = colaboradoresComUsuarios.Foto,
               

            };

            if (colaboradoresComUsuarios != null)
            {
                return View(colaboradoresView);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AlterarColaboradores(ColaboradoresEdicaoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var colaboradores = await _unitOfwork.ColaboradoresServices.ObterPorId(model.Id);
                    if (colaboradores != null)
                    {
                        var usuario = await _unitOfwork.UserServices.ObterPorUserId(colaboradores.UserId);

                        if (usuario != null)
                        {

                           
                            usuario.PrimeiroNome = model.NomeCompleto;
                            colaboradores.Foto = model.Foto;
                            
                            await _unitOfwork.ColaboradoresServices.Atualizar(colaboradores);
                            await _unitOfwork.UserServices.Atualizar(usuario);
                        }
                    }
                    else
                    {
                        ViewBag.Msg = "Não há dados.";
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<JsonResult> ExcluirColaborador(int id)
        {
            try
            {
                var colaborador = await _unitOfwork.ColaboradoresServices.ObterPorId(id);
                if (colaborador != null)
                {
                    await _unitOfwork.ColaboradoresServices.Deletar(id);
                    return Json(new { sucesso = true, mensagem = "Colaborador excluído com sucesso" });
                }
                else
                {
                    return Json(new { sucesso = false, mensagem = "Colaborador não existe" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { sucesso = false, mensagem = "Ocorreu um erro ao excluir o Colaborador: " + ex.Message });
            }
        }
    }
}

fourfit-sistema_gestao.UI/Views/Colaboradores/AlterarColaboradores.cshtml
@model ColaboradoresEdicaoViewModel
@{
    ViewData["Title"] = "AlterarColaborador";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form class="row g-3" asp-controller="Colaboradores" asp-action="AlterarColaboradores" method="post">
                <div class="form-group">
                    <label class="control-label">Foto</label>
                    <input type="file" asp-for="Foto" class="form-control" />
                    <span asp-validation-for="Foto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Nome Completo</label>
                    <input type="text" asp-for="NomeCompleto" class="form-control" />
                    <span asp-validation-for="NomeCompleto" class="text-danger"></span>
                </div>
                <div class="col-md-12">
                    <label for="Cpf" class="form-label">Cpf</label>
                    <input type="int" class="form-control">

                </div>

                <div class="col-md-12">
                    <label for="Observacaes" class="form-label">Observaçães</label>
                    <input type="text" class="form-control" asp-for="Observacaes">
                    <span asp-validation-for="Observacaes" class="text-danger"></span>
                </div>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
            </form>
        </div>
    </div>
</div>


<div>
    <a class="btn bnt-dark" asp-action="Index">Voltar</a>
</div>

fourfit-sistema_gestao.UI/Views/Colaboradores/CadastroColaboradores.cshtml
@model fourfit_sistema_gestao.UI.Models.Colaboradores.ColaboradoresViewModel

@{
    ViewData["Title"] = "CadastroColaboradores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CadastroColaboradores" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Foto</label>
                    <input type="file" asp-for="Foto" class="form-control" />
                    <span asp-validation-for="Foto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Id" class="control-label"></label>
                    <select asp-for="UserId" class="form-select" asp-items="@ViewBag.Usuario">
                        <option selected value="0">Selecione o Usuário</option>
                    </select>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>


            </form>
        </div>
    </div>
</div>


<div>
    <a class="btn bnt-dark" asp-action="Index">Voltar</a>
</div>

fourfit-sistema_gestao.UI/Views/Colaboradores/Index.cshtml
@model IEnumerable<EntidadeColaboradores>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
@Html.AntiForgeryToken()


<div class="container">
    <h2>Gerenciador de Colaboradores</h2>

    @* <div class="custom"></div>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <form class="form-inline d-flex" method="get" action="@Url.Action("Index", "Colaboradores")">

            <input type="text" class="form-control mr-2" placeholder="Pesquisar Colaborador..." name="searchString" value="@ViewBag.CurrentFilter">
            <button type="submit" class="btn btn-outline-dark">Buscar</button>

        </form>
        @if(User.IsInRole("Colaboradores") || User.IsInRole("Admin") )
        {
             <button type="button" onclick="location.href='@Url.Action("CadastroColaboradores","Colaboradores")'" class="btn btn-outline-dark"> <i class="bi bi-plus"></i> Novo Colaborador</button>
        }
      
    </div>

    <br /><br />
</div>
<div class="card">


    <div class="card-header">
        <div class="card-title">
        </div>
    </div>
    <div class="card-body">
        @TempData["Msg"]
        <table class="table">
            <thead>
                <tr>
                    <th>Foto</th>
                    <th>Nome</th>
                    <th>Status</th>
                    <th>Cpf</th>
                    <th>Observaçães</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @if (@Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Foto</td>
                            <td>@item.User.NomeCompleto</td>


                            @if (item.Ativo == true)
                            {
                                <td style="color:darkslategrey">ATIVO</td>
                            }
                            else
                            {
                                <td style="color:red">INATIVO</td>
                            }
                            <td>@item.Cpf</td>
                            <td>@item.Observacaes</td>
                            <td>
                                <button class="btn btn-outline-warning" title="Editar" onclick="window.location.href ='@Url.Action("AlterarColaboradores","Colaboradores", new {Id = item.Id})'">
                                    <i class="fa-solid fa-user-pen"></i>
                               </button>
                                <button class="btn btn-outline-danger btnExcluir" title="Excluir" data-id="@item.Id"><i class="fa-solid fa-user-xmark"></i></button>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
    </div>*@

</div> 

@section scripts {
    <script>

        $('.btnExcluir').on('click', function () {
            if (confirm("Deseja excluir?")) {
                var id = $(this).attr("data-id");
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("ExcluirColaborador", "Colaboradores")',
                    data: { Id: id },
                    success: function (response) {
                        if (response.sucesso) {
                            alert(response.mensagem);
                            window.location.href = '@Url.Action("Index", "Colaboradores")';

                        }

                    }, error: function () {

                    }
                });
            }


        });

    </script>
}